name: UltimateSheepWars
author: Royalpha
version: 5.0.7
main: fr.royalpha.sheepwars.core.SheepWarsPlugin
softdepend: [Vault]
website: https://therenceforot.fr/ultimate-sheep-wars
commands:
  ultimatesheepwars:
    description: Manage your ultimate sheepwars in-game settings
    aliases: [ultimatesw, usw, sheepwars, sw]
  lang:
    description: Change your language
    aliases: [language, langage]
  stats:
    description: Check player stats
  hub:
    description: Return to hub
  contributor:
    aliases: [contrib, c]
    description: Only for contributors
permissions:
  usw.admin:
    description: Become an administrator of sheepwars
    default: op
  usw.teams.bypass:
    description: Bypass team conditions 
  usw.login.bypass:
    description: Bypass login restrictions
  sheepwars.kit.morehealth:
    description: Unlock the More health kit
  sheepwars.kit.betterbow:
    description: Unlock the Better bow kit
  sheepwars.kit.bettersword:
    description: Unlock the Better sword kit
  sheepwars.kit.moresheep:
    description: Unlock the More sheep kit
  sheepwars.kit.builder:
    description: Unlock the Builder kit
  sheepwars.kit.mobility:
    description: Unlock the Mobility kit
  sheepwars.kit.armoredsheep:
    description: Unlock the Armored sheep kit